### ISSUE TITLE
Update requirements to reflect updated bounds for pyhf v0.7.0

### ISSUE THREAD

**Issue by matthewfeickert** [conda-forge/pyhf-feedstock#12]
As a TODO list item for @matthewfeickert during the `pyhf` `v0.7.0` release, the minimum required dependencies versions

https://github.com/conda-forge/pyhf-feedstock/blob/4be38287f0899a69388ca6fe33ee2db622736500/recipe/meta.yaml#L19-L32

have been [updated for `pyhf` `v0.7.0`](https://github.com/scikit-hep/pyhf/blob/v0.7.0/setup.cfg#L30-L42) and should now be

```yaml
requirements:
  host:
    - python >=3.7
    - pip
    - attrs>=17.1
    - setuptools_scm[toml] >=3.4
    - setuptools_scm_git_archive >=1.0
  run:
    - python >=3.7
    - scipy >=1.1.0
    - click >=7.0
    - tqdm >=4.56.0
    - jsonschema >=3.0.0
    - jsonpatch >=1.15
    - pyyaml >=5.1
```

(adding `attrs` and updating `scipy`).
